export const mockUser = {
  id: 'user_1',
  email: 'demo@devstash.io',
  name: 'John Doe',
  isPro: true,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-06-01'),
}

export const mockItemTypes = [
  {
    id: 'type_1',
    name: 'snippet',
    icon: 'Code',
    color: '#3b82f6',
    isSystem: true,
  },
  {
    id: 'type_2',
    name: 'prompt',
    icon: 'Sparkles',
    color: '#8b5cf6',
    isSystem: true,
  },
  {
    id: 'type_3',
    name: 'command',
    icon: 'Terminal',
    color: '#f97316',
    isSystem: true,
  },
  {
    id: 'type_4',
    name: 'note',
    icon: 'StickyNote',
    color: '#fde047',
    isSystem: true,
  },
  {
    id: 'type_5',
    name: 'file',
    icon: 'File',
    color: '#6b7280',
    isSystem: true,
  },
  {
    id: 'type_6',
    name: 'image',
    icon: 'Image',
    color: '#ec4899',
    isSystem: true,
  },
  {
    id: 'type_7',
    name: 'link',
    icon: 'Link',
    color: '#10b981',
    isSystem: true,
  },
]

export const mockCollections = [
  {
    id: 'col_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    itemCount: 12,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    itemCount: 8,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    itemCount: 5,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_4',
    name: 'Interview Prep',
    description: 'Technical interview preparation',
    isFavorite: false,
    itemCount: 24,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_5',
    name: 'Git Commands',
    description: 'Frequently used git commands',
    isFavorite: true,
    itemCount: 15,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_6',
    name: 'AI Prompts',
    description: 'Curated AI prompts for coding',
    isFavorite: false,
    itemCount: 18,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-01'),
  },
]

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'TEXT',
    content: 'const useAuth = () => {\n // authentication logic here\n};',
    description: 'Custom React hook for authentication logic',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'auth', 'hooks'],
    createdAt: '2026-03-16',
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    description: 'Fetch wrapper with exponential backoff retry logic',
    contentType: 'TEXT',
    content: 'const fetchWithRetry = async (url, options) => {\n // retry logic here\n};',
    isFavorite: false,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['api', 'error-handling'],
    createdAt: '2026-03-18',
  },
  {
    id: 'item_3',
    title: 'Git Rebase Workflow',
    description: 'Step-by-step rebase and squash workflow',
    itemTypeId: 'type_3',
    collectionId: 'col_5',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['git', 'workflow'],
    createdAt: '2026-03-10',
  },
  {
    id: 'item_4',
    title: 'Python List Comprehension',
    description: 'Advanced list comprehension patterns',
    itemTypeId: 'type_1',
    collectionId: 'col_2',
    isFavorite: false,
    isPinned: false,
    language: 'python',
    tags: ['python', 'patterns'],
    createdAt: '2026-03-12',
  },
  {
    id: 'item_5',
    title: 'Code Review Prompt',
    description: 'AI prompt for thorough code review feedback',
    itemTypeId: 'type_5',
    collectionId: 'col_6',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['ai', 'code-review'],
    createdAt: '2026-03-14',
  },
  {
    id: 'item_6',
    title: 'Docker Compose Cheatsheet',
    description: 'Common docker compose commands and flags',
    itemTypeId: 'type_3',
    collectionId: null,
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['docker', 'devops'],
    createdAt: '2026-03-08',
  },
  {
    id: 'item_7',
    title: 'System Design Template',
    description: 'Template for system design interview answers',
    itemTypeId: 'type_note',
    collectionId: 'col_4',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['interview', 'system-design'],
    createdAt: '2026-03-05',
  },
  {
    id: 'item_8',
    title: 'Next.js Middleware Auth',
    description: 'Middleware pattern for route protection in Next.js',
    itemTypeId: 'type_1',
    collectionId: 'col_1',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    tags: ['nextjs', 'auth', 'middleware'],
    createdAt: '2026-03-20',
  },
  {
    id: 'item_9',
    title: 'Prisma Schema Reference',
    description: 'Quick reference for Prisma schema syntax',
    itemTypeId: 'type_url',
    collectionId: null,
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['prisma', 'database'],
    createdAt: '2026-03-11',
  },
  {
    id: 'item_10',
    title: 'Architecture Diagram',
    description: 'DevStash system architecture overview',
    itemTypeId: 'type_image',
    collectionId: 'col_3',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['architecture', 'diagram'],
    createdAt: '2026-03-15',
  },
  {
    id: 'item_11',
    title: 'Cursor Rules Template',
    description: 'Template for .cursorrules file',
    itemTypeId: 'type_file',
    collectionId: 'col_3',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['ai', 'cursor'],
    createdAt: '2026-03-09',
  },
  {
    id: 'item_12',
    title: 'Explain Code Prompt',
    description: 'Prompt for detailed code explanations with examples',
    itemTypeId: 'type_prompt',
    collectionId: 'col_6',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['ai', 'prompts'],
    createdAt: '2026-03-17',
  },
]

export const mockItemTypeCounts = {
  snippet: 4,
  prompt: 1,
  command: 2,
  note: 1,
  file: 1,
  image: 1,
  link: 1,
}