export const mockUser = {
  id: 'user_1',
  email: 'demo@devstash.io',
  name: 'John Doe',
  isPro: true,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-06-01'),
}

export const mockItemTypes = [
  {
    id: 'type_1',
    name: 'snippet',
    icon: 'Code',
    color: '#3b82f6',
    isSystem: true,
  },
  {
    id: 'type_2',
    name: 'prompt',
    icon: 'Sparkles',
    color: '#8b5cf6',
    isSystem: true,
  },
  {
    id: 'type_3',
    name: 'command',
    icon: 'Terminal',
    color: '#f97316',
    isSystem: true,
  },
  {
    id: 'type_4',
    name: 'note',
    icon: 'StickyNote',
    color: '#fde047',
    isSystem: true,
  },
  {
    id: 'type_5',
    name: 'file',
    icon: 'File',
    color: '#6b7280',
    isSystem: true,
  },
  {
    id: 'type_6',
    name: 'image',
    icon: 'Image',
    color: '#ec4899',
    isSystem: true,
  },
  {
    id: 'type_7',
    name: 'link',
    icon: 'Link',
    color: '#10b981',
    isSystem: true,
  },
]

export const mockCollections = [
  {
    id: 'col_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    itemCount: 5,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    itemCount: 3,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    itemCount: 2,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_4',
    name: 'Interview Prep',
    description: 'Technical interview preparation',
    isFavorite: false,
    itemCount: 3,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_5',
    name: 'Git Commands',
    description: 'Frequently used git commands',
    isFavorite: true,
    itemCount: 3,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'col_6',
    name: 'AI Prompts',
    description: 'Curated AI prompts for coding',
    isFavorite: true,
    itemCount: 4,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-01'),
  },
]

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'TEXT',
    content: 'const useAuth = () => {\\n  // authentication logic here\\n};',
    description: 'Custom React hook for authentication logic',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    collectionId: 'col_1',
    tags: ['react', 'auth', 'hooks'],
    createdAt: '2026-03-16',
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    contentType: 'TEXT',
    content:
      'const fetchWithRetry = async (url, options) => {\\n  // retry logic here\\n};',
    description: 'Fetch wrapper with exponential backoff retry logic',
    isFavorite: true,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    collectionId: 'col_1',
    tags: ['api', 'error-handling'],
    createdAt: '2026-03-18',
  },
  {
    id: 'item_3',
    title: 'Git Rebase Workflow',
    contentType: 'TEXT',
    content:
      'git fetch origin\\ngit rebase -i origin/main\\n# squash commits if needed\\ngit push --force-with-lease',
    description: 'Step-by-step rebase and squash workflow',
    itemTypeId: 'type_3',
    collectionId: 'col_5',
    isFavorite: false,
    isPinned: true,
    language: null,
    tags: ['git', 'workflow'],
    createdAt: '2026-03-10',
  },
  {
    id: 'item_4',
    title: 'Python List Comprehension',
    contentType: 'TEXT',
    content:
      '[user.email for user in users if user.is_active]\\n{name: score for name, score in results if score > 90}',
    description: 'Advanced list comprehension patterns',
    itemTypeId: 'type_1',
    collectionId: 'col_2',
    isFavorite: true,
    isPinned: false,
    language: 'python',
    tags: ['python', 'patterns'],
    createdAt: '2026-03-12',
  },
  {
    id: 'item_5',
    title: 'Code Review Prompt',
    contentType: 'TEXT',
    content:
      'Review this code for bugs, edge cases, readability, performance, and maintainability. Give concrete suggestions and examples.',
    description: 'AI prompt for thorough code review feedback',
    itemTypeId: 'type_2',
    collectionId: 'col_6',
    isFavorite: true,
    isPinned: true,
    language: null,
    tags: ['ai', 'code-review'],
    createdAt: '2026-03-14',
  },
  {
    id: 'item_6',
    title: 'Docker Compose Cheatsheet',
    contentType: 'TEXT',
    content:
      'docker compose up -d\\ndocker compose down\\ndocker compose logs -f\\ndocker compose exec app sh',
    description: 'Common docker compose commands and flags',
    itemTypeId: 'type_3',
    collectionId: null,
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['docker', 'devops'],
    createdAt: '2026-03-08',
  },
  {
    id: 'item_7',
    title: 'System Design Template',
    contentType: 'TEXT',
    content:
      '1. Clarify requirements\\n2. Estimate scale\\n3. High-level design\\n4. Data model\\n5. Bottlenecks\\n6. Tradeoffs',
    description: 'Template for system design interview answers',
    itemTypeId: 'type_4',
    collectionId: 'col_4',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['interview', 'system-design'],
    createdAt: '2026-03-05',
  },
  {
    id: 'item_8',
    title: 'Next.js Middleware Auth',
    contentType: 'TEXT',
    content:
      'export function middleware(req) {\\n  // route protection logic\\n}',
    description: 'Middleware pattern for route protection in Next.js',
    itemTypeId: 'type_1',
    collectionId: 'col_1',
    isFavorite: false,
    isPinned: true,
    language: 'typescript',
    tags: ['nextjs', 'auth', 'middleware'],
    createdAt: '2026-03-20',
  },
  {
    id: 'item_9',
    title: 'Prisma Schema Reference',
    contentType: 'URL',
    content: 'https://www.prisma.io/docs/orm/prisma-schema',
    description: 'Quick reference for Prisma schema syntax',
    itemTypeId: 'type_7',
    collectionId: null,
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['prisma', 'database'],
    createdAt: '2026-03-11',
  },
  {
    id: 'item_10',
    title: 'Architecture Diagram',
    contentType: 'IMAGE',
    content: '/images/devstash-architecture.png',
    description: 'DevStash system architecture overview',
    itemTypeId: 'type_6',
    collectionId: 'col_3',
    isFavorite: true,
    isPinned: true,
    language: null,
    tags: ['architecture', 'diagram'],
    createdAt: '2026-03-15',
  },
  {
    id: 'item_11',
    title: 'Cursor Rules Template',
    contentType: 'FILE',
    content: '.cursorrules',
    description: 'Template for .cursorrules file',
    itemTypeId: 'type_5',
    collectionId: 'col_3',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['ai', 'cursor'],
    createdAt: '2026-03-09',
  },
  {
    id: 'item_12',
    title: 'Explain Code Prompt',
    contentType: 'TEXT',
    content:
      'Explain this code step by step, including what each function does, why it exists, and a simple example of usage.',
    description: 'Prompt for detailed code explanations with examples',
    itemTypeId: 'type_2',
    collectionId: 'col_6',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['ai', 'prompts'],
    createdAt: '2026-03-17',
  },
  {
    id: 'item_13',
    title: 'React Performance Checklist',
    contentType: 'TEXT',
    content:
      'Use memo, useCallback, lazy loading, and avoid unnecessary re-renders.',
    description: 'Checklist for optimizing React performance',
    itemTypeId: 'type_4',
    collectionId: 'col_1',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['react', 'performance'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_14',
    title: 'React Debug Prompt',
    contentType: 'TEXT',
    content:
      'Analyze this React component and identify unnecessary re-renders and performance issues.',
    description: 'Prompt to debug React performance',
    itemTypeId: 'type_2',
    collectionId: 'col_1',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['react', 'ai'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_15',
    title: 'Python Debug Command',
    contentType: 'TEXT',
    content: 'python -m pdb script.py',
    description: 'Run Python debugger from CLI',
    itemTypeId: 'type_3',
    collectionId: 'col_2',
    isFavorite: false,
    isPinned: true,
    language: 'python',
    tags: ['python', 'debug'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_16',
    title: 'Python Docs',
    contentType: 'URL',
    content: 'https://docs.python.org/3/',
    description: 'Official Python documentation',
    itemTypeId: 'type_7',
    collectionId: 'col_2',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['python', 'docs'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_17',
    title: 'System Design Prompt',
    contentType: 'TEXT',
    content:
      'Design a scalable system for X. Include tradeoffs, bottlenecks, and scaling strategy.',
    description: 'Prompt for practicing system design interviews',
    itemTypeId: 'type_2',
    collectionId: 'col_4',
    isFavorite: true,
    isPinned: true,
    language: null,
    tags: ['interview', 'system-design'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_18',
    title: 'Big O Cheat Sheet',
    contentType: 'IMAGE',
    content: '/images/big-o.png',
    description: 'Common time complexity reference chart',
    itemTypeId: 'type_6',
    collectionId: 'col_4',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['algorithms', 'complexity'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_19',
    title: 'Undo Last Commit',
    contentType: 'TEXT',
    content: 'git reset --soft HEAD~1',
    description: 'Undo last commit but keep changes staged',
    itemTypeId: 'type_3',
    collectionId: 'col_5',
    isFavorite: true,
    isPinned: true,
    language: null,
    tags: ['git'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_20',
    title: 'Git Docs',
    contentType: 'URL',
    content: 'https://git-scm.com/docs',
    description: 'Official Git documentation',
    itemTypeId: 'type_7',
    collectionId: 'col_5',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['git', 'docs'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_21',
    title: 'Refactor Prompt',
    contentType: 'TEXT',
    content:
      'Refactor this code to improve readability, maintainability, and performance. Keep functionality unchanged.',
    description: 'Prompt for code refactoring',
    itemTypeId: 'type_2',
    collectionId: 'col_6',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['ai', 'refactor'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_22',
    title: 'AI Prompt Guidelines',
    contentType: 'FILE',
    content: '/files/prompt-guidelines.md',
    description: 'Best practices for writing AI prompts',
    itemTypeId: 'type_5',
    collectionId: 'col_6',
    isFavorite: false,
    isPinned: true,
    language: null,
    tags: ['ai', 'guide'],
    createdAt: '2026-03-21',
  },
  {
    id: 'item_23',
    title: 'Quick JSON Parse',
    contentType: 'TEXT',
    content: 'const data = JSON.parse(jsonString);',
    description: 'Simple JSON parsing snippet',
    itemTypeId: 'type_1',
    collectionId: null,
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    tags: ['json'],
    createdAt: '2026-03-22',
  },
  {
    id: 'item_24',
    title: 'Daily Dev Notes',
    contentType: 'TEXT',
    content: 'Remember to review PRs and clean up unused branches.',
    description: 'General development reminder',
    itemTypeId: 'type_4',
    collectionId: null,
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['notes'],
    createdAt: '2026-03-22',
  },
]

export const mockItemTypeCounts = {
  snippet: 5,
  prompt: 5,
  command: 4,
  note: 3,
  file: 2,
  image: 2,
  link: 3,
}
